# Generated by Django 3.2.5 on 2021-07-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_alter_product_hunter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
