# Generated by Django 3.2.5 on 2021-07-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_product_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vodes_total',
            new_name='hunter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='product',
            name='votes_total',
            field=models.IntegerField(default=1),
        ),
    ]
