# Generated by Django 3.2.5 on 2021-07-28 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_auto_20210728_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='time',
        ),
    ]
