# Generated by Django 3.2.5 on 2021-07-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_alter_product_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
