# Generated by Django 3.2.5 on 2021-07-28 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0004_alter_product_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.TimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
