# Generated by Django 3.2.5 on 2021-07-28 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0004_remove_product_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hunter',
        ),
    ]
