# Generated by Django 3.2.5 on 2021-07-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0005_remove_product_hunter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(blank=True, default='default.png', upload_to='images/'),
        ),
    ]
